
version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
     

services:


  wg_dashboard:
    #depends_on: [unbound, adguard]
    build: .
    #image: noxcis/wg-dashboard:cetus
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./Global-Configs/Wiregate-Database:/home/app/db
      - ./Global-Configs/Master-Key:/home/app/master-key
      - ./Global-Configs/Firewall-Rules:/home/app/FIREWALLS
    environment:
      - WG_DASH_USER=admin
      - WG_DASH_PASS=admin
      - WG_DASH_SECRET_KEY=some-super-secret_key
      - WG_DASH_SERVER_IP=172.60.107.196
      - WG_DASH_DNS=10.2.0.100, 10.2.0.100
      - WG_DASH_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WG_DASH_KEEP_ALIVE=21
      - WG_DASH_MTU=1420
      - WG_DASH_PORT_RANGE_STARTPORT=770
    ports:
      - "770-775:770-775/udp"
      - 8080:10086/tcp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      private_network:
        ipv4_address: 10.2.0.3


  